# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'COVID' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Charts'
pod 'ChartsRealm'
pod 'TinyConstraints'
pod 'Alamofire', '~> 5.2' 
pod 'RxSwift', '~>5'
pod 'RxCocoa', '~>5'
pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
 # Pods for COVID
end
